from PyQt5 import QtCore, QtGui, QtWidgets
import pandas as pd
from datetime import date
from datetime import datetime

from safety import Ui_SafteyWindow
from recreation import Ui_rec
from PyQt5 import *
from swui import Ui_StateWise     
statewise=pd.read_csv("https://api.covid19india.org/csv/latest/state_wise.csv")
lastupdated=statewise['Last_Updated_Time'][0].split(' ')
timeob=datetime.strptime(lastupdated[1],"%H:%M:%S")
lastupdated=datetime.strptime(lastupdated[0],"%d/%m/%Y")
print("Active")
state=statewise.loc[statewise['State']=='Total']
total=int(state['Confirmed'])
recovered=int(state['Recovered'])
deceased=int(state['Deaths'])
active=int(state['Active'])
class Ui_MainWindow(object):
    def OpenStateWise(self):
        self.window = QtWidgets.QMainWindow()
        self.ui=Ui_StateWise()
        self.ui.setupUi(self.window)
        self.window.show()
        #MainWindow.hide()
    def OpenSafety(self):
        self.window = QtWidgets.QMainWindow()
        self.ui=Ui_SafteyWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        #MainWindow.hide()
    def OpenRec(self):
        self.window = QtWidgets.QMainWindow()
        self.ui=Ui_rec()
        self.ui.setupUi(self.window)
        self.window.show()
        #MainWindow.hide()    
        
    def setupUi(self, MainWindow):
        QtGui.QFontDatabase.addApplicationFont("Pictures/BankGothic Md BT.ttf")
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(558, 639)
        MainWindow.setFixedSize(MainWindow.size())
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 40, 500, 30))
        font = QtGui.QFont()
        font.setFamily("BankGothic Md BT")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 500, 30))
        font = QtGui.QFont()
        font.setFamily("BankGothic Md BT")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 160, 500, 30))
        font = QtGui.QFont()
        font.setFamily("BankGothic Md BT")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 120, 500, 30))
        font = QtGui.QFont()
        font.setFamily("BankGothic Md BT")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.openGLWidget.setGeometry(QtCore.QRect(-430, 730, 300, 200))
        self.openGLWidget.setObjectName("openGLWidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 220, 221, 161))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 220, 221, 161))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 410, 221, 161))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(300, 410, 221, 161))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 240, 200, 30))
        font = QtGui.QFont()
        font.setFamily("BankGothic Md BT")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 290, 330, 30))
        font = QtGui.QFont()
        font.setFamily("BankGothic Md BT")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 580, 200, 30))
        font = QtGui.QFont()
        font.setFamily("BankGothic Md BT")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(310, 580, 210, 30))
        font = QtGui.QFont()
        font.setFamily("BankGothic Md BT")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 558, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        MainWindow.setStyleSheet('background-color:#FFFFFF;background-image:url("Pictures/Screenshot (13).png");background-repeat:no-repeat;background-size:100%')
        self.pushButton_2.clicked.connect(self.OpenStateWise)
        self.pushButton_3.clicked.connect(self.OpenSafety)
        self.pushButton_4.clicked.connect(self.OpenRec)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "COVID-19 India Tracker"))
        self.label.setText(_translate("MainWindow", "Total Confirmed Cases: "+str(total)))
        self.label.setStyleSheet('color: #FF2D58;background-color: #F8CCCA;background-image:url("")')
        self.label_2.setText(_translate("MainWindow", "Total Active Cases: "+str(active)))
        self.label_2.setStyleSheet('color: #017CFF;background-color: #EFF7FF;background-image:url("")')
        self.label_3.setText(_translate("MainWindow", "Deceased Cases: "+str(deceased)))
        self.label_4.setStyleSheet('color:#29A746;background-color: #E4F4E8;background-image:url("") ')
        self.label_4.setText(_translate("MainWindow", "Recovered Cases: "+str(recovered)))
        self.label_3.setStyleSheet('color:#767E85;background-color: #F6F6F7;background-image:url("")')
        self.pushButton.setText(_translate("MainWindow", ""))
        self.pushButton.setStyleSheet('background-image:url("");background-color:transparent;background-position:center;background-repeat:no-repeat')
        self.pushButton_2.setText(_translate("MainWindow", ""))
        self.pushButton_2.setStyleSheet('background-image:url("Pictures/sa.png");background-color:transparent;background-position:center;background-repeat:no-repeat')
        self.pushButton_3.setText(_translate("MainWindow", ""))
        self.pushButton_3.setStyleSheet('background-image:url("Pictures/sf.png");background-color:transparent;background-position:center;background-repeat:no-repeat')
        self.pushButton_4.setText(_translate("MainWindow", ""))
        self.pushButton_4.setStyleSheet('background-image:url("Pictures/re.png");background-color:transparent;background-position:center;background-repeat:no-repeat')
        self.label_5.setText(_translate("MainWindow","Updated on:"))
        self.label_5.setStyleSheet('color:#4540B0;background-color: #E3E2F3;background-image:url("")')
        self.label_6.setText(_translate("MainWindow",lastupdated.strftime("%d")+","+lastupdated.strftime("%B")+" "+lastupdated.strftime("%y")+" | "+timeob.strftime("%I")+":"+timeob.strftime("%M")+timeob.strftime("%p")))
        self.label_6.setStyleSheet('color:#4540B0;background-color: #E3E2F3;background-image:url("")')
        self.label_7.setText(_translate("MainWindow"," Donate Now: "))
        self.label_7.setStyleSheet('color:#FD7F15;background-color: #FFF3D0;background-image:url("")')
        urlLink=" <a href=\"https://www.bhimupi.org.in/donation-digitized-with-bhim-upi\" style='text-decoration:none;color:#FD7F15'>&nbsp;pmcares@sbi</a>"
        self.label_8.setText(_translate("MainWindow",""+urlLink))
        self.label_8.setStyleSheet('color:#FD7F15;background-color: #FFF3D0;background-image:url("");text-decoration:none')
        self.label_8.setOpenExternalLinks(True)
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QtGui.QIcon('Pictures/virus.ico'))
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
