# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recreation.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_rec(object):
    def setupUi(self, rec):
        QtGui.QFontDatabase.addApplicationFont("Pictures/BankGothic Md BT.ttf")
        rec.setObjectName("rec")
        rec.resize(782, 600)
        rec.setFixedSize(rec.size())
        rec.setStyleSheet("background-color:#EFF7FF;")
        self.centralwidget = QtWidgets.QWidget(rec)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 520, 761, 22))
        self.horizontalSlider.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.horizontalSlider.setStyleSheet("background-color:transparent;")
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setSingleStep(10)
        self.horizontalSlider.setProperty("value", 20)
        self.horizontalSlider.setSliderPosition(0)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider.setTickInterval(10)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(60, 480, 55, 51))
        font = QtGui.QFont()
        font.setFamily("BankGothic Md BT")
        font.setPointSize(12)
        self.label_1.setFont(font)
        self.label_1.setStyleSheet("background-color:transparent;")
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setWordWrap(True)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 480, 55, 51))
        font = QtGui.QFont()
        font.setFamily("BankGothic Md BT")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:transparent;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(210, 480, 55, 51))
        font = QtGui.QFont()
        font.setFamily("BankGothic Md BT")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color:transparent;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(280, 480, 55, 51))
        font = QtGui.QFont()
        font.setFamily("BankGothic Md BT")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color:transparent;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(360, 480, 55, 51))
        font = QtGui.QFont()
        font.setFamily("BankGothic Md BT")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color:transparent;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(430, 480, 55, 51))
        font = QtGui.QFont()
        font.setFamily("BankGothic Md BT")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color:transparent;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(510, 480, 55, 51))
        font = QtGui.QFont()
        font.setFamily("BankGothic Md BT")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color:transparent;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(580, 480, 55, 51))
        font = QtGui.QFont()
        font.setFamily("BankGothic Md BT")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color:transparent;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(660, 480, 55, 51))
        font = QtGui.QFont()
        font.setFamily("BankGothic Md BT")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color:transparent;")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(730, 480, 55, 51))
        font = QtGui.QFont()
        font.setFamily("BankGothic Md BT")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color:transparent;")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, 480, 55, 51))
        font = QtGui.QFont()
        font.setFamily("BankGothic Md BT")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:transparent;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(0, 0, 782, 50))
        font = QtGui.QFont()
        font.setFamily("BankGothic Md BT")
        font.setPointSize(18)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color:transparent;")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(0, 370, 782, 101))
        font = QtGui.QFont()
        font.setFamily("BankGothic Md BT")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color:#E3E2F3;color:#3D37AD;")
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_12.setWordWrap(True)
        self.label_12.setMargin(15)
        self.label_12.setIndent(3)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(30, 80, 331, 261))
        self.label_13.setStyleSheet("background-color:transparent;")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(420, 80, 331, 261))
        self.label_14.setStyleSheet("background-color:transparent;")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        rec.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(rec)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 782, 26))
        self.menubar.setObjectName("menubar")
        rec.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(rec)
        self.statusbar.setObjectName("statusbar")
        rec.setStatusBar(self.statusbar)
        self.horizontalSlider.valueChanged.connect(self.updateContent)
        self.retranslateUi(rec)
        QtCore.QMetaObject.connectSlotsByName(rec)
    def updateContent(self):
        val=self.horizontalSlider.value()     
        if(val%10!=0):
            val+=10-(val%10)
            self.horizontalSlider.setValue(val)  
        if(val==50):
           self.label_11.setText("Exercise")
           
           self.label_12.setText("It is probably the best time you can indulge in exercising and ensuring that you remain healthy and fit. You can either start a new form of exercise or continue with your old one, as per your wish. What’s best is that in both cases, you will work towards improving your immunity. ")
           self.label_13.setStyleSheet("background-image:url('Pictures/ex1.jpg')")
           self.label_14.setStyleSheet("background-image:url('Pictures/ex2.jpg')")
        if(val==10):
           self.label_11.setText("Play Games")
           self.label_12.setText("You can dedicate a specific time slot each day to play games such as hide and seek, charades, board games, Jenga, and numerous others with your entire family. ")
           self.label_13.setStyleSheet("background-image:url('Pictures/game1.jpg')")
           self.label_14.setStyleSheet("background-image:url('Pictures/game2.jpg')")
        if(val==20):
           self.label_11.setText("Watch Movies")
           self.label_12.setText("This is the idle time you can indulge in binge-watching old or new movies that you have never seen before. Pick a few good Hollywood or Bollywood movies, grab some popcorn and call your family members to engage in this fun activity.")
           self.label_13.setStyleSheet("background-image:url('Pictures/mv1.jpg')")
           self.label_14.setStyleSheet("background-image:url('Pictures/mv2.jpg')")
        if(val==30):
           self.label_11.setText("Cook Together")
           self.label_12.setText("We Indians love eating different types of recipes on a daily basis. You too can decide an everyday menu and indulge in cooking it together with your loved ones. This way, you would get time to increase your bond as well as satiate your desire for variety in food.")
           self.label_13.setStyleSheet("background-image:url('Pictures/ck1.jpg')")
           self.label_14.setStyleSheet("background-image:url('Pictures/ck2.jpg')")
        if(val==40):
           self.label_11.setText("Indulge in Gardening")
           self.label_12.setText("Being among plants and trees gives us a sense of relief. You along with your dear ones can get involved in a gardening activity to give back the most to nature. Planting new seeds, controlling weeds, adding some garden art, and others are a few gardening activities you can engage in. ")
           self.label_13.setStyleSheet("background-image:url('Pictures/ga1.jpg')")
           self.label_14.setStyleSheet("background-image:url('Pictures/ga2.jpg')")
        if(val==0):
           self.label_11.setText("Pamper your pets")
           self.label_11.setStyleSheet("background-color:#e0efff;color:#1485FF")
           self.label_12.setText("If you are lucky to have pets in your home, give some time of your day to interact with them. In fact, your whole family can play along with your pets or pamper them to make them feel special the same way they make you do.")
           self.label_13.setStyleSheet("background-image:url('Pictures/pet1.jpg');")
           self.label_14.setStyleSheet("background-image:url('Pictures/pet2.jpg');background-repeat:no-repeat")
        if(val==60):
           self.label_11.setText("Reconnect with old friends and colleagues")
           self.label_12.setText("Coronavirus lockdown is the idle time you can reestablish the connection with long lost friends and old colleagues that once were a dear part of your life. ")
           self.label_13.setStyleSheet("background-image:url('Pictures/f1.jpg')")
           self.label_14.setStyleSheet("background-image:url('Pictures/f2.jpg')")
        if(val==70):
           self.label_11.setText("Explore your artistic side")
           self.label_12.setText("Try your hand at painting, sketching, photography, doodling, quilling, paper cutting, writing poems & songs, etc. Choosing any of the creative activities will grant you peace of mind as well as do complete justice to your free time ")
           self.label_13.setStyleSheet("background-image:url('Pictures/ar1.jpg')")
           self.label_14.setStyleSheet("background-image:url('Pictures/ar2.jpg')")
        if(val==80):
           self.label_11.setText("Revisit memories")
           self.label_12.setText("In your daily life, you may not get a chance to bring back the old times. But, you can recall them by looking at your old family photographs or videos together.  ")
           self.label_13.setStyleSheet("background-image:url('Pictures/rl1.jpg')")
           self.label_14.setStyleSheet("background-image:url('Pictures/rl2.jpg')")
        if(val==90):
           self.label_11.setText("Meditate")
           self.label_12.setText("If you want to experience mental and physical peace, put on some music and give meditation a try. Meditation will also help you reduce stress, increase energy, enhance immunity system, and benefit in a lot more ways. ")
           self.label_13.setStyleSheet("background-image:url('Pictures/m1.jpg')")
           self.label_14.setStyleSheet("background-image:url('Pictures/m2.jpg')")
        if(val==100):
           self.label_11.setText("Practice dance")
           self.label_12.setText("Whether or not you are a fan of dancing, give it a try. You can also learn a new form of dance. It will not only improve your mood, health and fitness but also help you increase your confidence. ")
           self.label_13.setStyleSheet("background-image:url('Pictures/d1.jpg')")
           self.label_14.setStyleSheet("background-image:url('Pictures/d2.jpg')")                            
    def retranslateUi(self, rec):
        _translate = QtCore.QCoreApplication.translate
        rec.setWindowTitle(_translate("rec", "Recreational Activities"))
        self.label_1.setText(_translate("rec", "1"))
        self.label_2.setText(_translate("rec", "2"))
        self.label_3.setText(_translate("rec", "3"))
        self.label_4.setText(_translate("rec", "4"))
        self.label_5.setText(_translate("rec", "5"))
        self.label_6.setText(_translate("rec", "6"))
        self.label_7.setText(_translate("rec", "7"))
        self.label_8.setText(_translate("rec", "8"))
        self.label_9.setText(_translate("rec", "9"))
        self.label_10.setText(_translate("rec", "10"))
        self.label.setText(_translate("rec", "0"))
        self.updateContent()
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QtGui.QIcon('Pictures/virus.ico'))
    rec = QtWidgets.QMainWindow()
    ui = Ui_rec()
    ui.setupUi(rec)
    rec.show()
    sys.exit(app.exec_())
