from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SafteyWindow(object):
    def setupUi(self, SafteyWindow):
        QtGui.QFontDatabase.addApplicationFont("Data/BankGothic Md BT.ttf")
        SafteyWindow.setObjectName("SafteyWindow")
        SafteyWindow.resize(768, 913)
        SafteyWindow.setFixedSize(SafteyWindow.size())
        self.centralwidget = QtWidgets.QWidget(SafteyWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 744, 858))
        self.scrollAreaWidgetContents.setMouseTracking(True)
        self.scrollAreaWidgetContents.setTabletTracking(True)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(170, 50, 561, 91))
        self.label.setStyleSheet("background-color:#EFF7FF;color:#439DFF")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setIndent(3)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(11, 11, 151, 131))
        self.label_2.setMaximumSize(QtCore.QSize(351, 16777215))
        self.label_2.setStyleSheet("background-color:pink")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(10, 430, 151, 131))
        self.label_3.setMaximumSize(QtCore.QSize(351, 16777215))
        self.label_3.setStyleSheet("background-color:pink")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(10, 290, 151, 131))
        self.label_4.setMaximumSize(QtCore.QSize(351, 16777215))
        self.label_4.setStyleSheet("background-color:pink")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setEnabled(True)
        self.label_5.setGeometry(QtCore.QRect(10, 150, 151, 131))
        self.label_5.setMaximumSize(QtCore.QSize(351, 16777215))
        self.label_5.setStyleSheet("background-color:pink")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setGeometry(QtCore.QRect(170, 190, 561, 91))
        self.label_7.setStyleSheet("background-color:#EFF7FF;color:#439DFF")
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_7.setIndent(3)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setGeometry(QtCore.QRect(170, 330, 561, 91))
        self.label_8.setStyleSheet("background-color:#EFF7FF;color:#439DFF")
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_8.setIndent(3)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setGeometry(QtCore.QRect(170, 470, 561, 91))
        self.label_9.setStyleSheet("background-color:#EFF7FF;color:#439DFF")
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_9.setIndent(3)
        self.label_9.setObjectName("label_9")
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setEnabled(True)
        self.label_6.setGeometry(QtCore.QRect(10, 570, 151, 131))
        self.label_6.setMaximumSize(QtCore.QSize(351, 16777215))
        self.label_6.setStyleSheet("background-color:pink")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setEnabled(True)
        self.label_10.setGeometry(QtCore.QRect(10, 710, 151, 131))
        self.label_10.setMaximumSize(QtCore.QSize(351, 16777215))
        self.label_10.setStyleSheet("background-color:pink")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setGeometry(QtCore.QRect(170, 750, 561, 91))
        self.label_11.setStyleSheet("background-color:#EFF7FF;color:#439DFF")
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_11.setIndent(3)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setGeometry(QtCore.QRect(170, 610, 561, 91))
        self.label_12.setStyleSheet("background-color:#EFF7FF;color:#439DFF")
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_12.setIndent(3)
        self.label_12.setObjectName("label_12")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("BankGothic Md BT")
        font.setPointSize(16)
        self.label_13.setFont(font)
        self.label_13.setTextFormat(QtCore.Qt.PlainText)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 0, 1, 1)
        SafteyWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SafteyWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 768, 26))
        self.menubar.setObjectName("menubar")
        SafteyWindow.setMenuBar(self.menubar)
        SafteyWindow.setStyleSheet("background-color:white;font-family:BankGothic Md BT;font-size:16px")
        self.retranslateUi(SafteyWindow)
        QtCore.QMetaObject.connectSlotsByName(SafteyWindow)

    def retranslateUi(self, SafteyWindow):
        _translate = QtCore.QCoreApplication.translate
        SafteyWindow.setWindowTitle(_translate("SafteyWindow", "Safety Measures"))
        font = QtGui.QFont()
        font.setFamily("BankGothic Md BT")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        
        self.label.setWordWrap(True) 
        self.label_7.setWordWrap(True)
        self.label_8.setWordWrap(True)
        self.label_9.setWordWrap(True)
        self.label_12.setWordWrap(True)
        self.label_11.setWordWrap(True)
        
        self.label.setText(_translate("SafteyWindow", "<span style='color:black;font-size:18px'><b>Wash your hands often </b></span>"+"with soap and water for at least 20 seconds, especially after being in a public place, or after blowing your nose, coughing or sneezing. If soap and water are not readily available, use a hand sanitizer with at least 60% alcohol."))
        self.label_2.setText(_translate("SafteyWindow", ""))
        self.label_2.setStyleSheet("background-image:url('Pictures/hand-wash.png');background-position:center;background-repeat:no-repeat;background-color:pink")
        self.label_3.setText(_translate("SafteyWindow", ""))
        self.label_3.setStyleSheet("background-image:url('Pictures/cough.png');background-position:center;background-repeat:no-repeat;background-color:pink")
        self.label_4.setText(_translate("SafteyWindow", ""))
        self.label_4.setStyleSheet("background-image:url('Pictures/social.png');background-position:center;background-repeat:no-repeat;background-color:pink")
        self.label_8.setText(_translate("SafteyWindow", "<span style='color:black;font-size:18px'><b>Practice social distancing </b></span>")+"by keeping at least 6 feet — about two arm lengths — away from others if you must go out in public. Stay connected with loved ones through video and phone calls, texts and social media. Avoid close contact with people who are sick.")
        self.label_5.setText(_translate("SafteyWindow", ""))
        self.label_5.setStyleSheet("background-image:url('Pictures/spread.png');background-position:center;background-repeat:no-repeat;background-color:pink")
        self.label_7.setText(_translate("SafteyWindow", "<span style='color:black;font-size:18px'><b>Stay home </b></span>"+"if you can and avoid any non-essential travel. Avoid social gatherings of more than 10 people."))
        self.label_9.setText(_translate("SafteyWindow", "<span style='color:black;font-size:18px'><b>Cover your coughs and sneezes </b></span>"+"Use a tissue to cover your nose and mouth and throw used tissues in a lined trash can. If a tissue isn’t available, cough or sneeze into your elbow — not your hands. Wash your hands immediately."))
        self.label_6.setText(_translate("SafteyWindow", ""))
        self.label_6.setStyleSheet("background-image:url('Pictures/cleaning.png');background-position:center;background-repeat:no-repeat;background-color:pink")
        self.label_10.setText(_translate("SafteyWindow", ""))
        self.label_10.setStyleSheet("background-image:url('Pictures/quarantine.png');background-position:center;background-repeat:no-repeat;background-color:pink")
        self.label_11.setText(_translate("SafteyWindow", "<span style='color:black;font-size:18px'><b>Self Quarantine </b></span>"+"in your home. On your own, clean and disinfect all surfaces daily and high-touch surfaces frequently throughout the day in your sick room and designated bathroom. Have a healthy household member do the same for surfaces in other parts of the home."))
        self.label_12.setText(_translate("SafteyWindow", "<span style='color:black;font-size:18px'><b>Clean and disinfect household surfaces </b></span>"+"daily and high-touch surfaces frequently throughout the day. High-touch surfaces include phones, remote controls, counters, tabletops, doorknobs, bathroom fixtures, toilets, keyboards, tablets and bedside tables. Follow CDC guidance."))
        self.label_13.setText(_translate("SafteyWindow", "Saftey Measures"))
        self.label_13.setStyleSheet("background-color:pink;font-size:30px;color:#FF083B")
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QtGui.QIcon('Pictures/virus.ico'))
    SafteyWindow = QtWidgets.QMainWindow()
    ui = Ui_SafteyWindow()
    ui.setupUi(SafteyWindow)
    SafteyWindow.show()
    sys.exit(app.exec_())
